### ISSUE TITLE
is it possible to run this demo with two cameras instead of four?

### ISSUE THREAD

**Issue by glenosborne** [RidgeRun/gtc-2020-demo#2]
hi i am very interested in learning about this demo and underlying technology.
I am trying to run the sample with TX2 jp 4.4 using two cameras,
one that is on the TX2 board and another high quality high spec usb based camera.
both stream to the screen for 4- 8 seconds before it crashes.

is there a place to specify two cameras instead of four and can you direct me to more tutorials i can look at to learn more about gst-interpipe, deepstream and Gstreamer.

gst-inspect-1.0 interpipe
shows the expected output

i have run some basic tests to ensure GStreamer is working,
is there some other  test i can run to ensure its working correctly for this sample

the more i read through the code the more i want to know

regards

**Comment by jcaballeros** [comment]
Hi glenosborne,

The media server doesn't have a built-in option to change the number of cameras, for that purpose I recommend to take a look at the deepstream pipeline element nvstreammux:

https://github.com/RidgeRun/gtc-2020-demo/blob/master/python-example/media-server.py#L56

You can check our developer wikis:

[GstInterpipe](https://developer.ridgerun.com/wiki/index.php?title=GstInterpipe)
[GStreamer_Daemon](https://developer.ridgerun.com/wiki/index.php?title=GStreamer_Daemon)
[DeepStream pipelines](https://developer.ridgerun.com/wiki/index.php?title=DeepStream_pipelines)

When working with DeepStream, bear in mind that as JP4.4 brings a new version (5.0) the config files might not work out of the box with the pipelines on the wiki, since those were created for a previous DeepStream version.
